/** Supported contributor API. Historical ./search exports remain available for compatibility. */
export { ComponentRegistry } from '../evolution/components.js'
export { componentRef } from '../evolution/component-ref.js'
export { implementationFromFiles } from '../evolution/implementation-files.js'
export type { ComponentImplementation } from '../evolution/component-ref.js'
export type { ComponentRef } from '../types.js'
export { createParentRandom } from './parent-random.js'
export type { ParentRandom } from './parent-random.js'
export { parentSelectionInput, selectParentsWithPolicy, validateParentPlan } from './parent-selection.js'
export type { ParentSelectionPolicy, ParentSelectionInput, ParentSelectionPlan, ParentAllocation, ParentOption, ParentScopeOption } from './parent-selection.js'
export { SearchStore } from './store.js'
export type { SearchJournal, RemainingBudget, Usage } from './store.js'
export type { SearchAdmission, SearchExecutionHooks, GeneratedCandidate } from './runtime.js'
export type { SearchRoundOutcome } from './engine.js'
export type { SearchProvider, CellVerification, DiagnosisProvider, SearchConfig, SearchSettings, Snapshot, TaskUniverse, EvidenceCell, StageEvaluationPlan, StageResult, ParentSelectionDecision } from './types.js'
